language: node_js
os:
- linux
node_js:
- 8
- 10
- stable
before_install:
  - npm i npm@latest -g
deploy:
  provider: npm
  on:
    tags: true
  skip_cleanup: true
  email:
    secure: LxLUHADDxN10tR9WPLMLA51UJW6EiRrFbWrNG1WZfxqkM9SER19ec6vNCJy+wrRI5gs+6dvezZMZHE9c4Ezhh96Qauj3g1hD1IcReHdiYIZWp96kZr39olOCsqCdcOuxmrZg+4ae4j1KdJNLBup46Jr5UYWvcmTv+/OzOKmz+DJMyP5I01cJv1XVb46xCwNNy9rzUvVuIpDLBVnEw0q0kkG7XHVyCGuCKJSsmBnnDW4ysZ1RmyDU6q70tLb5du8oYyTcJZg8Y7PbWAjuNTBUl7+rvLsTNAKSiSGOokFPu0et4tmI6XPQps8bgriaspoX1c7Bmfxndq5OuDRt5A1rO+4OWBY7hY5KFmd4vLJeBn3LDFi/BcZ2N2666Re+m2AX/f2DQPzbcEiADj0yKxAkkIwWAmBg9uZsvOzRZ39URtObLD+7056kCpuCXsxN6xxzNa4pOsKxxsalDUQuf68gJ8OeW9oDlCoM37q0waO127ZnXBAtm25St8qw/H/brMjS3rsmJsyu3dLJNpAkojTC/BPg9QlAuVoBOgHrAPvQAWum/Vl02o+3FS5gavxT7qu0Qofw14BXSzSxN9o7Wpkq7nBeLV3UEUgk041cl/cmNTMTOJN/sRcZMOPbDlHgn5OK9CN626yBgPHthDRLflMMmUUTbNtgxsaSnjVsQ6nRlKQ=
  api_key:
    secure: J13GPTP7CEW96td4jYHt4W0RJYSwCaXgvIVk8voxtNbY8ATEwHNHrK24DNDwyrqWSZW5wpkHJx45ImzNBQaWXGrxmglQjeol9ZOl0XC+T3TqoeBcAB101Nsw6eOzgdmimJ9DxRgZqm0nheMuoVqokg05pxr0dnAu6BEg9GOKX4AL5Vh9ZmmTi/JGENhR7edg57ghOcAY0FRNieKBOjkpUb5RG7tGV27Q00tABBGze97OdCFVqPjv2hM5hkyymVpzZ55AR22iwNFPFpIM/YfusD2cW8mBcaWQQQy38Ts5S9Bh3yVHcZHfUw0PYQ9R5MwYjZDsDe07YKIiYJdLvAicp48YiG7TPt3lz2tkfFu3tNRsFmkHIHZzLIkwhoEqzVQ7Elg1dNrA2ITtnfPBTvw/gNY+BB0WzQZPyWywX3meUPq56z1VZ7hrdYCwenJF5g+u/77mE81PdZeLTDj49i3qSpOwc44TqEMQ/KQdSk9Tuy5ukJugGWGj5yzextFL03ay9jZdkSGE6R8ehJUjGJeKovZ69pf7VMkR331UAq3RTvCMgjk9MvSvh1TPC793PYnUQgZX9XfKVSnoauL/3Eop7nwBdDRQZqn/nTaj7t+p/vCe0r5Vgpl10x9+ZvR1KlPeo8luOOvSLcjWmrcShSO/MvNSQjvvlA33I7Dee3MqDrY=
