language: node_js
os:
- linux
node_js:
- 8
- 10
- stable
deploy:
  provider: npm
  on:
    tags: true
  skip_cleanup: true
  email:
    secure: O/nWpsqKxFWkO8+ltRdeNkTzBJMuuTbCMPcKrTQsTPxVIOh3XGwFX6OOGVWFxNugcMyEXT6gfq57FS1BtqxUaMKISqs4Rby6qyJ1puxwECz27jcVteCFUQ3Ykpxj/iMs+RMIweJfSI8q3RbfFm+LB2WlKgvJn94nIP+4BZBdwUmy0Ehxx32MOWLTfkRlFPDfugl1XcL0CfDpFeW4SYw9AVODMtTfmVg2Wcq8DXuFdfi6Ydlbfb/MlG2GuND6Z021yHoH+YIcWpoz2/nXKpmHNln8LFF0fxC0DLlLjTeW9BRDn/r+t+78Sq9lgC6kBh0yxX6DKY4yNt5HTADZeSnlFUUMWNkvJ970v3dZU0Gr/tqatAKytLoE2QuJBejQxFGoxNNHG2NcVOxdIToiywe/VSv+SuYFJ5tIERbSZ0HRbnoog0KOr5Z5x3knK41nICM1O17Cm5lhyFJe+3Pxl0BE7oZK9N67EoLmMfCHQB1c55wdjFjc/HbvLm79ggcBEpNijqUScAXBVE+h7oba1j4j7kkMz31+IitfE80JF5bSgnMB6GhBJyHJRSmPUNfEqKX1LyL2zKcOuQwOEmWcA6s7lB8o0CtbGAyH3shJ3bfRNTO4hciV/nlRP4VMyBGwZPmp7EqjqXdCd0z4e3bW41cetT3ZOCRCBg10qU+E/VLVQWo=
  api_key:
    secure: uwRpXP6owoLrDY/Y21iUG8Se3nUToygD6JwS8V3C04testZ+qhVIVpR8Wnks5sq4Ib4U85Pv8NX3iTEicgyUfyA0pE2ox3/eHnMy9I/qamzniwbN4oPykdSd1gcTvNY8mYCqRl8KiCoGTceXTBMmhJ+aQwdUXo4ycUFVP7z25nySYsElDW4REtogew0DUbzEIJe42xcCQjKdu3ABOs17uFVEzCYtcXFXx/OglEPLSWVXMlvynHLCFq7pcF2ooKqOM5UDT7saV+aTUCLM+001aBevmnWYCJvii6MowvU6KuRpA3G3xM7Ns9yWjNWKEX1kslGO+/GdU9P+XfoXOKVfUJiCYsrOBlPu/nFvl8gB1epBf5BSCBtM5Kefkp77lVIz7hUOq9VzdxRIf42xOCf67ZtH7258Ng/RvjZV0xlvikqmCVeXA5J5NOG6u1EGQ5nMiVWdg3NQavGcTZv0s4o73OxcnFRE6vGf69wEMirpGpOc6k+f4cwGGYTvkfrbR2AsZD+bYXw5TvGch3ydw2vE8yRYTQ+THHD0vZj7CLWij2vWbf+2DmoWDR38QtI6ZZhY9q5Neo3PEjHeevLY/NfHUL9RZ8rkCt3p7Oq+aP29EDrx/GGgg9KOdAuXBzCXNLMTlM2fjCR1vOkDMnxd04nEdikFUkpNiAcw2FiVGhVsiyU=
